FROM python:3.13.12-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y --no-install-recommends \
    git \
    hyperfine \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
RUN uv pip install --system pydocstring-rs

RUN mkdir -p /workspace

WORKDIR /workspace
